main: noelle.loaders.paper.PaperLoader
name: ${plugin.name}

load: STARTUP
description: ${plugin.description}

version: ${plugin.version}
api-version: 1.18

website: "https://github.com/iwmc-git/noELLE"
authors: ["nightlyDuck", "sBwAeBeYt"]