main: noelle.loaders.paper.PaperLoader
name: ${name}

load: STARTUP
description: ${description}

version: ${version}
api-version: 1.18

website: "https://github.com/iwmc-git/noELLE"
authors: ["nightlyDuck", "sBwAeBeYt"]